Workflow: enable matrix (#107)
## PR Checklist

- [x] All commits must be signed
- [ ] Appropriate pytests were added
- [ ] Documentation is updated

diff --git a/.github/workflows/build-and-test-mac.yml b/.github/workflows/build-and-test-mac.yml
--- a/.github/workflows/build-and-test-mac.yml
+++ b/.github/workflows/build-and-test-mac.yml
@@ -19,8 +19,8 @@ jobs:
         include:
           - os: macos-14
             artifact_name: dmgs-arm64
-          # - os: macos-13
-          #   artifact_name: dmgs-x86_64
+          - os: macos-13
+            artifact_name: dmgs-x86_64
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -63,9 +63,9 @@ jobs:
           - arch: arm64
             runner: macos-15  # This runner must be an arm64 machine
             artifact_name: dmgs-arm64
-          # - arch: x86_64
-          #   runner: macos-13    # This runner must be an x86 machine
-          #   artifact_name: dmgs-x86_64
+          - arch: x86_64
+            runner: macos-13    # This runner must be an x86 machine
+            artifact_name: dmgs-x86_64
     runs-on: ${{ matrix.runner }}
     steps:
       - name: Download DMG Artifact for ${{ matrix.arch }}
@@ -143,6 +143,14 @@ jobs:
           
         shell: bash
 
+
+      - name: Check for pyzbar log entry in bitcoin_safe.log
+        run: |
+          echo "Checking bitcoin_safe.log for 'pyzbar could be loaded successfully'..." | tee -a test_dmg.log
+          if ! grep -q "pyzbar could be loaded successfully" "/Users/runner/Library/Application Support/bitcoin_safe/bitcoin_safe.log"; then
+            echo "Error: 'pyzbar could be loaded successfully' not found in bitcoin_safe.log" | tee -a test_dmg.log
+            exit 1
+          fi
 
       - name: Gatekeeper tests on ${{ matrix.arch }}
         run: |
