added lib can the workflow be triggered manually?

diff --git a/.github/workflows/build-appimage-test.yml b/.github/workflows/build-appimage-test.yml
--- a/.github/workflows/build-appimage-test.yml
+++ b/.github/workflows/build-appimage-test.yml
@@ -2,14 +2,14 @@ name: Build AppImage Test
 
 on:
   workflow_dispatch:
-  pull_request:
-    types: [labeled]
-    branches:
-      - main
+    inputs:
+      input:
+        description: "Test"
+        required: false
+        default: ""
 
 jobs:
   build:
-    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'run-build-test')  
     runs-on: ubuntu-latest
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -64,3 +64,51 @@ jobs:
             echo "AppImage file is missing"
             exit 1
           fi
+
+
+      # - name: Install Dependencies for gui test
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y xvfb libfuse2 xdotool
+      #   shell: bash
+
+      # - name: Start Xvfb
+      #   run: Xvfb :99 -screen 0 1024x768x16 &
+      #   env:
+      #     DISPLAY: ":99"
+                
+      # - name: Run AppImage
+      #   run: |
+      #     APPIMAGE=$(find ./dist -maxdepth 1 -name "*.AppImage" | head -n 1)
+      #     if [ -z "$APPIMAGE" ]; then
+      #       echo "No AppImage file found in ./dist/"
+      #       exit 1
+      #     fi
+      #     echo "Running AppImage: $APPIMAGE"
+      #     chmod +x "$APPIMAGE"
+      #     "$APPIMAGE" &
+      #   env:
+      #     DISPLAY: ":99"
+
+
+      # - name: Wait for Application to Start
+      #   run: sleep 5
+
+      # - name: Check for Application Window
+      #   run: |
+      #     WINDOW_NAME="Bitcoin Safe"
+      #     WINDOW_ID=$(xdotool search --name "$WINDOW_NAME")
+      #     if [ -z "$WINDOW_ID" ]; then
+      #       echo "Application window not found."
+      #       exit 1
+      #     else
+      #       echo "Application window found with ID: $WINDOW_ID"
+      #     fi
+      #   env:
+      #     DISPLAY: ":99"
+
+      # - name: Close Application
+      #   run: |
+      #     xdotool search --name "Bitcoin Safe" windowkill %@ || true
+      #   env:
+      #     DISPLAY: ":99"
